---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: registry-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

images:
  - name: registry
    newTag: "2.8"

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - ingress.yaml
  - service.yaml
  - configmap.yaml
  - deployment.yaml
