---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: git

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: git-secret-tls
    type: kubernetes.io/tls
    files:
      - tls.crt
      - tls.key

images:
  - name: gitea/gitea
    newTag: "1.22"

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - ingress.yaml
  - service.yaml
  - deployment.yaml
