---
- name: Disable services
  ansible.builtin.service:
    name: "{{ item }}"
    state: stopped
    enabled: false
  failed_when: false
  notify:
    - Reboot
  loop: "{{ awx_on_k3s_disable_services }}"

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - git
      - curl
    state: present

- name: Ensure python packages are installed
  ansible.builtin.pip:
    name:
      - cryptography
      - kubernetes
      - kubernetes-validate
    state: present
...
