---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: awx

generatorOptions:
  disableNameSuffixHash: true

#secretGenerator:
#  - name: awx-secret-tls
#    type: kubernetes.io/tls
#    files:
#      - tls.crt
#      - tls.key

resources:
  - pv.yaml
  - pvc.yaml
